version: "2"
services:
  zookeeper:
    image: luckyj5/zookeeper
    hostname: zookeeper
    restart: always

  kafka:
    image: luckyj5/kafka
    hostname: kafka
    restart: always
    links:
      - zookeeper

  kafka-data-gen:
    image: luckyj5/kafka-data-gen
    hostname: kafka-data-gen
    links:
      - kafka
    restart: always
    environment:
    - KAFKA_MSG_COUNT=1000000
    - KAFKA_MSG_SIZE=256
    - KAFKA_TOPIC=perf
    - KAFKA_BATCH_SIZE=16384
    - KAFKA_BUFFER_MEMORY=33554432

  kafka-conect-splunk-sink:
    image: luckyj5/kafka-connect-splunk-sink
    hostname: kafka-connect
    links:
      - kafka-data-gen
    restart: always
    environment:
    - SPLUNK_HEC_ENDPOINT=https://<spluk-hec-endpoint>:8088
    - SPLUNK_HEC_TOKEN=<splunk-hec-token>
    - KAFKA_TOPIC=perf
