version: "2"
services:
  zookeeper:
    image: luckyj5/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: luckyj5/kafka
    hostname: kafka
    restart: always
    links:
      - zookeeper
  kafka-data-gen:
    image: luckyj5/kafka-data-gen
    hostname: kafka-data-gen
    links:
      - kafka
    restart: always